const $ = id => document.getElementById(id);
let mode = 'offline'; let account = null; let skinImage = null; let model = 'CLASSIC'; let nextMove = 0; let moveStrength = 2; let installedTargets = new Set(); let busy = false;
function showPage(name) { const pages = new Set(['home', 'play', 'mods', 'account', 'console', 'mod-detail']); const target = pages.has(name) ? name : 'home'; document.querySelectorAll('[data-page]').forEach(page => page.classList.toggle('active', page.dataset.page === target)); document.querySelectorAll('[data-page-link]').forEach(link => link.classList.toggle('active', link.dataset.pageLink === target)); if (target !== 'mod-detail') history.replaceState(null, '', `#${target}`); window.scrollTo({ top: 0, behavior: 'smooth' }); }
document.querySelectorAll('[data-page-link]').forEach(link => link.addEventListener('click', event => { event.preventDefault(); showPage(link.dataset.pageLink); }));
window.addEventListener('hashchange', () => showPage(location.hash.slice(1) || 'home'));
const log = (message, kind = '') => { const node = $('log'); node.textContent += `\n${new Date().toLocaleTimeString()} ${kind ? `[${kind}] ` : ''}${message}`; node.scrollTop = node.scrollHeight; };
function updateMemory() { $('memoryValue').textContent = `${$('memory').value} MB`; }
function loadSkin(url) { skinImage = null; if (!url) return; const image = new Image(); image.crossOrigin = 'anonymous'; image.onload = () => { skinImage = image; }; image.onerror = () => log('皮肤预览图片加载失败。', 'warn'); image.src = url; }
function profileUI() { const online = mode === 'online'; $('offlinePanel').hidden = online; $('onlinePanel').hidden = !online; document.querySelectorAll('.mode').forEach(b => b.classList.toggle('active', b.dataset.mode === mode)); $('accountBadge').textContent = online ? (account ? '正版已登录' : '等待登录') : '离线模式'; $('profileName').textContent = online && account ? account.name : ($('username').value.trim() || 'Player'); }
function setModel(next, persist = false) { model = next; document.querySelectorAll('.model').forEach(b => b.classList.toggle('active', b.dataset.model === model)); if (persist && account) window.liteMC.setSkinModel(model).then(setAccount).catch(e => log(e.message, 'error')); }
function setAccount(next) { account = next; if (account) { model = account.variant === 'SLIM' ? 'SLIM' : 'CLASSIC'; loadSkin(account.skinUrl); } else loadSkin(null); $('login').textContent = account ? '退出 Microsoft 帐号' : '登录 Microsoft 帐号'; profileUI(); setModel(model); }
const targetKey = () => `${$('loader').value}:${$('version').value}`;
const loaderNames = { vanilla: '原版', fabric: 'Fabric + API', forge: 'Forge', liteloader: 'LiteLoader', optifine: 'OptiFine' };
let loaderCapabilities = [], capabilityVersion = '', capabilityRequest = 0;
async function refreshLoaderCapabilities() {
  const version = $('version').value, request = ++capabilityRequest;
  try {
    const items = await window.liteMC.getLoaders(version);
    if (request !== capabilityRequest) return;
    loaderCapabilities = items; capabilityVersion = version; updateVersionState();
  } catch (error) { log(`加载器状态不可用：${error.message}`, 'warn'); }
}
function updateVersionState() {
  const loader = $('loader').value, version = $('version').value;
  const installed = installedTargets.has(targetKey()), loaderName = loaderNames[loader] || loader;
  const capability = capabilityVersion === version ? loaderCapabilities.find(item => item.id === loader) : null;
  const supported = capability?.automaticInstall === true;
  $('versionState').textContent = capability && !supported ? capability.reason : installed ? `${loaderName} 已安装` : `${loaderName} ${capability ? '尚未安装' : '正在检查支持状态…'}`;
  $('installVersion').textContent = installed ? '检查 / 修复安装' : `下载 ${loaderName}`;
  $('installVersion').disabled = busy || !supported;
  $('launch').disabled = busy || !installed || !supported;
  $('searchMods').disabled = busy || !supported || !['fabric', 'forge'].includes(loader);
  if (capabilityVersion !== version) { capabilityVersion = version; loaderCapabilities = []; refreshLoaderCapabilities(); }
}
function drawSkin() { const c = $('skinPreview'), x = c.getContext('2d'); x.clearRect(0, 0, 160, 190); const t = performance.now() / 1000; if (t > nextMove) { moveStrength = 1 + Math.random() * 2.5; nextMove = t + 2.5 + Math.random() * 4; } const bob = Math.sin(t * 1.2) * .8; const swing = Math.sin(t * 1.2) * moveStrength; x.save(); x.translate(80, 15 + bob); x.imageSmoothingEnabled = false; const sourceArmW = model === 'SLIM' ? 3 : 4; const armW = model === 'SLIM' ? 11 : 14;
  const part = (sx, sy, sw, sh, dx, dy, dw, dh) => skinImage ? x.drawImage(skinImage, sx, sy, sw, sh, dx, dy, dw, dh) : (x.fillStyle = '#7ac49c', x.fillRect(dx, dy, dw, dh));
  part(8, 8, 8, 8, -20, 0, 40, 40); part(20, 20, 8, 12, -20, 40, 40, 60);
  x.save(); x.translate(-20 - armW / 2, 42); x.rotate(swing * Math.PI / 180); part(44, 20, sourceArmW, 12, -armW / 2, 0, armW, 58); x.restore();
  x.save(); x.translate(20 + armW / 2, 42); x.rotate(-swing * Math.PI / 180); part(36, 52, sourceArmW, 12, -armW / 2, 0, armW, 58); x.restore();
  part(4, 20, 4, 12, -20, 100, 19, 60); part(20, 52, 4, 12, 1, 100, 19, 60); x.restore(); requestAnimationFrame(drawSkin); }
async function refreshInstalledMods() { const loader = $('loader').value; if (!['fabric', 'forge'].includes(loader)) { $('installedMods').textContent = '选择 Fabric 或 Forge 后可查看该版本的 Mod。'; return; } try { const mods = await window.liteMC.listMods({ version: $('version').value, loader }); $('installedMods').textContent = mods.length ? `已安装 Mod（${mods.length}）：${mods.join('、')}` : '这个版本还没有安装 Mod。'; } catch (e) { $('installedMods').textContent = `无法读取 Mod：${e.message}`; } }
async function init() { const settings = await window.liteMC.getSettings(); $('username').value = settings.username; $('memory').value = settings.memory; $('javaPath').value = settings.javaPath; $('language').value = settings.language || 'zh_cn'; $('loader').value = loaderNames[settings.loader] ? settings.loader : 'vanilla'; mode = settings.accountMode || 'offline'; updateMemory(); profileUI(); if (mode === 'online') { try { setAccount(await window.liteMC.getAccount()); } catch (e) { log(`无法恢复微软登录：${e.message}`, 'warn'); } } try { const data = await window.liteMC.getVersions({ offline: mode === 'offline', version: settings.version }); installedTargets = new Set(); data.versions.forEach(v => Object.entries(v.installed || {}).forEach(([loader, installed]) => { if (installed) installedTargets.add(`${loader}:${v.id}`); })); $('version').innerHTML = ''; [data.latest.release, ...data.versions.map(v => v.id).filter(v => v !== data.latest.release)].forEach((id, i) => { const option = document.createElement('option'); option.value = id; option.textContent = i ? id : `最新正式版 (${id})`; $('version').append(option); }); $('version').value = settings.version === 'latest-release' ? data.latest.release : settings.version; if (!$('version').value) $('version').value = data.latest.release; updateVersionState(); } catch (e) { $('version').innerHTML = '<option value="latest-release">最新正式版</option>'; log(`无法加载版本列表：${e.message}`, 'error'); } try { const key = await window.liteMC.getCurseForgeKeyStatus(); $('curseForgeKeyState').textContent = key.configured ? '已安全保存' : '尚未配置'; } catch {} await refreshInstalledMods(); drawSkin(); }
$('username').addEventListener('input', profileUI); $('memory').addEventListener('input', updateMemory);
$('version').addEventListener('change', () => { updateVersionState(); refreshInstalledMods(); }); $('loader').addEventListener('change', () => { updateVersionState(); refreshInstalledMods(); });
document.querySelectorAll('.mode').forEach(button => button.onclick = async () => { mode = button.dataset.mode; profileUI(); if (mode === 'online' && !account) { try { setAccount(await window.liteMC.getAccount()); } catch (e) { log(`无法恢复微软登录：${e.message}`, 'warn'); } } });
document.querySelectorAll('.model').forEach(button => button.onclick = () => setModel(button.dataset.model, true));
$('login').onclick = async () => { $('login').disabled = true; try { if (account) { await window.liteMC.logout(); setAccount(null); log('已退出微软帐号。', 'info'); } else { setAccount(await window.liteMC.login()); mode = 'online'; profileUI(); log('微软帐号登录成功，之后启动器会自动恢复登录。', 'info'); } } catch (e) { log(`帐号操作失败：${e.message || e}`, 'error'); } finally { $('login').disabled = false; } };
$('uploadSkin').onclick = async () => { try { setAccount(await window.liteMC.uploadSkin(model)); log('皮肤已上传到 Minecraft 官方服务。', 'info'); } catch (e) { log(e.message, 'error'); } };
$('folder').onclick = () => window.liteMC.openFolder(); $('clear').onclick = () => $('log').textContent = '';
$('pickJava').onclick = async () => { const picked = await window.liteMC.pickJava(); if (picked) $('javaPath').value = picked; };
 $('installVersion').onclick = async () => { busy = true; $('downloadProgress').value = 0; updateVersionState(); try { const result = await window.liteMC.installVersion({ version: $('version').value, loader: $('loader').value }); installedTargets.add(`${result.loader}:${result.version}`); if (result.javaPath) $('javaPath').value = result.javaPath; $('downloadProgress').value = 100; log(`${result.version} · ${loaderNames[result.loader] || result.loader} 与对应运行时下载完成。`, 'info'); } catch (e) { log(`版本下载失败：${e.message}`, 'error'); } finally { busy = false; updateVersionState(); } };
$('launch').onclick = async () => { const button = $('launch'); button.disabled = true; $('status').textContent = '正在准备游戏文件…'; try { await window.liteMC.launch({ username: $('username').value, accountMode: mode, version: $('version').value, loader: $('loader').value, memory: $('memory').value, javaPath: $('javaPath').value, language: $('language').value }); } catch (e) { $('status').textContent = `启动失败：${e.message}`; log(e.stack || e.message, 'error'); button.disabled = false; } };
$('modSource').onchange = () => { $('curseForgeSetup').hidden = $('modSource').value !== 'curseforge'; };
$('saveCurseForgeKey').onclick = async () => { try { await window.liteMC.setCurseForgeKey($('curseForgeKey').value); $('curseForgeKey').value = ''; $('curseForgeKeyState').textContent = '已安全保存'; log('CurseForge API Key 已使用系统安全存储保存。', 'info'); } catch (e) { log(e.message, 'error'); } };
$('searchMods').onclick = async () => { const button = $('searchMods'); button.disabled = true; $('modResults').innerHTML = '<div class="empty-mods">正在搜索兼容版本…</div>'; try { const items = await window.liteMC.searchMods({ source: $('modSource').value, query: $('modQuery').value, version: $('version').value, loader: $('loader').value }); renderMods(items); } catch (e) { $('modResults').innerHTML = `<div class="empty-mods error-text">${escapeText(e.message)}</div>`; } finally { button.disabled = false; updateVersionState(); } };
$('modQuery').addEventListener('keydown', event => { if (event.key === 'Enter') $('searchMods').click(); });
$('openMods').onclick = async () => { try { const result = await window.liteMC.openModsFolder({ version: $('version').value, loader: $('loader').value }); log(`已打开 Mods 文件夹：${result.path}`, 'info'); } catch (e) { log(e.message, 'error'); } };
function escapeText(value) { const node = document.createElement('span'); node.textContent = String(value || ''); return node.innerHTML; }
async function installMod(item, button) { if (button) { button.disabled = true; button.textContent = '安装中'; } try { const result = await window.liteMC.installMod({ source: item.source, id: item.id, version: $('version').value, loader: $('loader').value }); if (button) button.textContent = '已安装'; log(`${result.name} 已放入 Mods 文件夹。`, 'info'); await refreshInstalledMods(); } catch (e) { if (button) { button.disabled = false; button.textContent = '重试'; } log(`Mod 安装失败：${e.message}`, 'error'); } }
function renderModDetail(item) { const icon = item.iconUrl ? `<img src="${escapeText(item.iconUrl)}" alt="">` : 'M'; const link = item.pageUrl && /^https:\/\//.test(item.pageUrl) ? `<a class="ghost small" href="${escapeText(item.pageUrl)}" target="_blank" rel="noreferrer">打开项目页 ↗</a>` : ''; $('modDetailContent').innerHTML = `<div class="mod-detail-hero"><div class="mod-detail-icon">${icon}</div><div><div class="card-kicker">${escapeText(item.source || 'MOD')}</div><h2>${escapeText(item.title)}</h2><p>${escapeText(item.author || '未知作者')} · ${Number(item.downloads || 0).toLocaleString()} 下载</p></div></div><div class="mod-detail-description"><h3>项目说明</h3><p>${escapeText(item.description || '该项目没有提供简介。')}</p></div><div class="mod-detail-actions">${link}<button id="installDetailMod" class="install">安装到当前 ${loaderNames[$('loader').value] || '加载器'} 实例</button></div>`; $('installDetailMod').onclick = () => installMod(item, $('installDetailMod')); showPage('mod-detail'); }
function renderMods(items) { if (!items.length) { $('modResults').innerHTML = '<div class="empty-mods">没有找到兼容结果，试试更短的关键词。</div>'; return; } $('modResults').innerHTML = items.map((item, index) => `<article class="mod-item"><div class="mod-icon">${item.iconUrl ? `<img src="${escapeText(item.iconUrl)}" alt="">` : 'M'}</div><div class="mod-copy"><strong>${escapeText(item.title)}</strong><span>${escapeText(item.author)} · ${Number(item.downloads).toLocaleString()} 下载</span><p>${escapeText(item.description)}</p></div><div class="mod-item-actions"><button class="ghost small mod-detail-button" data-index="${index}">详情</button><button class="install mod-install" data-index="${index}">安装</button></div></article>`).join(''); document.querySelectorAll('.mod-install').forEach(button => button.onclick = () => installMod(items[Number(button.dataset.index)], button)); document.querySelectorAll('.mod-detail-button').forEach(button => button.onclick = () => renderModDetail(items[Number(button.dataset.index)])); }
$('mod-detail').querySelector('.back-to-mods').onclick = () => showPage('mods');
window.liteMC.onLog(value => log(value.message, value.type)); window.liteMC.onInstallProgress(value => { const current = Number(value.current ?? value.task ?? 0); const total = Number(value.total || 0); if (total > 0) $('downloadProgress').value = Math.min(100, current / total * 100); }); window.liteMC.onStatus(value => { $('status').textContent = value.text; busy = value.running; updateVersionState(); }); showPage(location.hash.slice(1) || 'home'); init();
